#! /bin/bash

export PARASOUL_DEAULT_LIST_DELIMITER="${PARASOUL_DEAULT_LIST_DELIMITER:-${IFS}}"
export PARASOUL_DEAULT_REPLACE_TOKEN="${PARASOUL_DEAULT_REPLACE_TOKEN:-"{}"}"
export PARASOUL_DEAULT_LIST_EACH_SLICE="${PARASOUL_DEAULT_LIST_EACH_SLICE:-"1"}"
export PARASOUL_DEAULT_JOBS="${PARASOUL_DEAULT_JOBS:-"1"}"
export PARASOUL_DEAULT_QUIET_MODE="${PARASOUL_DEAULT_QUIET_MODE:-"0"}"

trap parasoul::exit HUP INT QUIT TERM

parasoul::version() {
    echo "parasoul v0.0.1"
}
parasoul::help() {
cat << HELP >&2
USAGE:

  parasoul [OPTIONS] -- [CMDTEMPLATE] # Run the command in parallel

OPTIONS:

  * [-h|--help]                             # Show this help.
  * [-j|--jobs] job-count                   # Execute in parallel with \`job-count\`
  * [-V|--version]                          # Show parasoul version info.
  * [-p|--pipe]                             # Pipe mode
  * [-d|--delimiter]                        # Specify list delimiter (default: IFS)
  * [-l|--list]                             # List
  * [-q|--quiet]                            # Quiet mode

HELP
}

parasoul::exit() {
    parasoul::reccursive_ps_killer $$
}

parasoul::reccursive_ps_killer() {
    local target_ps=$1
    for x in $(ps --ppid ${target_ps} --no-heading | awk '{ print $1 }'); do
        parasoul::reccursive_ps_killer "${x}"
    done
    kill -9 ${target_ps}
}

parasoul::list() {
    PARASOUL_EXEC_LIST=${PARASOUL_EXEC_LIST:-""}
    if [ -p /dev/stdin ]; then
        ## pipe
        PARASOUL_EXEC_LIST="$(cat -)"
    fi

    if [[ ${PARASOUL_EXEC_LIST} = "" ]];then
        echo "Error: list not given." >&2
        exit 1
    fi
}

parasoul::job_pack() {
    local repo=${TARGET_REPOSITORIES[0]}
    TARGET_REPOSITORIES=("${TARGET_REPOSITORIES[@]:1}")
    if [[ -d ${repo} ]];then
        exec {FD}< <(parasoul::execute "${repo}")
        FD_LIST=(${FD_LIST[@]} ${FD})
    fi
}

parasoul::main() {
    FD_LIST=()

    parasoul::command
    parasoul::color
    parasoul::find_targets

    if [[ ${PARASOUL_DEAULT_SILENT_MODE} = FALSE ]];then
        echo "start parallel: ${PARASOUL_EXEC_CMD} ";
        echo;
    fi

    while true; do
        for x in $(seq "${PARASOUL_DEAULT_JOBS}"); do
            parasoul::job_pack
        done
        wait

        if [[ ${PARASOUL_DEAULT_SILENT_MODE} = TRUE ]];then
            for x in ${FD_LIST[@]}; do
                : <&${x}
            done
        else
            for x in ${FD_LIST[@]}; do
                cat <&${x}
            done
        fi

        if [[ -z ${TARGET_REPOSITORIES} ]];then
            break
        fi
    done
}


optspec=":j:m:c:d:F:-:hvVlsq"
while getopts "$optspec" optchar; do
    case "${optchar}" in
        -)
            case "${OPTARG}" in
                help)
                    exit 1
                    ;;
                version)
                    exit 1
                    ;;
                delimiter)
                    exit 1
                    ;;
                pipe)
                    exit 1
                    ;;
                replace-token)
                    exit 1
                    ;;
                list)
                    exit 1
                    ;;
                jobs)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    if [[ ${val} =~ ^[[:digit:]]+$ ]]; then
                        PARASOUL_DEAULT_JOBS="${val}"
                    else
                        echo "Unknown option --jobs ${val}" >&2
                        exit 1
                    fi
                    ;;
                quiet)
                    PARASOUL_DEAULT_QUIET_MODE="0"
                    ;;
                *)
                    echo "Unknown option --${OPTARG}" >&2
                    exit 1
                    ;;
            esac;;
        h)
            exit 1
            ;;
        V)
            exit 1
            ;;
        d)
            exit 1
            ;;
        p)
            exit 1
            ;;
        I)
            exit 1
            ;;
        l)
            exit 1
            ;;
        j)
            if [[ ${OPTARG} =~ ^[[:digit:]]+$ ]]; then
                PARASOUL_DEAULT_JOBS="${OPTARG}"
            else
                echo "Unknown option -j ${OPTARG}" >&2
                exit 1
            fi
            ;;
        d)
            exit 1
            ;;
        q)
            exit 1
            ;;
        v)
            exit 1
            ;;
        *)
            if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))

PARASOUL_EXEC_CMD=$@

if [[ -z ${PARASOUL_EXEC_CMD} ]];then
    exit 1
fi

parasoul::main && exit 0

