#! /bin/bash

ORIGIN_IFS="$IFS"
PARASOUL_ORIGINAL_REPLACE_TOKEN="{}"

export PARASOUL_DEAULT_LIST_DELIMITER="${PARASOUL_DEAULT_LIST_DELIMITER:-"(?:[\\n|\\t|\\s]+)"}"
export PARASOUL_DEAULT_REPLACE_TOKEN="${PARASOUL_DEAULT_REPLACE_TOKEN:-"${PARASOUL_ORIGINAL_REPLACE_TOKEN}"}"
export PARASOUL_DEAULT_JOBS="${PARASOUL_DEAULT_JOBS:-"2"}"
export PARASOUL_DEAULT_QUIET_MODE="${PARASOUL_DEAULT_QUIET_MODE:-"0"}"

trap parasoul::exit HUP INT QUIT TERM

parasoul::version() {
    echo "parasoul v0.0.1"
}

parasoul::help() {
cat << HELP >&2
USAGE:

  parasoul [OPTIONS] -- [CMDTEMPLATE] # Run the command in parallel

OPTIONS:

  * [-h|--help]                             # Show this help.
  * [-j|--jobs] job-count                   # Execute in parallel with \`job-count\`
  * [-v|--version]                          # Show parasoul version info.
  * [-p|--pipe]                             # Pipe mode
  * [-e|--command]                          # Specify list delimiter (default: \$IFS)
  * [-I|--replace-token]                    # Specify replace token
  * [-q|--quiet]                            # Quiet mode

HELP
}

parasoul::exit() {
    parasoul::reccursive_ps_killer $$
}

parasoul::reccursive_ps_killer() {
    local target_ps=$1
    for x in $(ps --ppid ${target_ps} --no-heading | awk '{ print $1 }'); do
        parasoul::reccursive_ps_killer "${x}"
    done
    kill -9 ${target_ps}
}

parasoul::list::generate() {
    PARASOUL_EXEC_LIST_STR="$@"
    if [ -p /dev/stdin ]; then
        ## pipe
        PARASOUL_EXEC_LIST_STR="$(cat -)"
    fi

    if [[ ${PARASOUL_EXEC_LIST_STR} = "" ]];then
        echo "Error: list not given." >&2
        exit 1
    fi
    PARASOUL_EXEC_LIST_STR=$(echo ${PARASOUL_EXEC_LIST_STR} | \
        perl -p -e 's/,/\[\[comma\]\]/g' | \
        perl -p -e "s/${PARASOUL_DEAULT_LIST_DELIMITER}/,/g")
    IFS="," PARASOUL_EXEC_LIST=( ${PARASOUL_EXEC_LIST_STR} )
    export IFS="${ORIGIN_IFS}"
}


list_dumper() {
    echo "------dump start"
    i=0
    for e in ${PARASOUL_EXEC_LIST[@]}; do
        echo "array[$i] = ${e}"
        let i++
    done
    echo "------dump end"
}

parasoul::exec::command() {
    local arg="$1"
    local cmd=$(echo ${PARASOUL_EXEC_CMD} | \
        perl -p -e 's/\[\[comma\]\]/,/g'| \
        perl -p -e "s/${PARASOUL_DEAULT_REPLACE_TOKEN}/${arg}/g" )
     parasoul::execute $cmd
}

parasoul::execute() {
    $@ 2>&1
}


parasoul::job_pack() {
    local item=${PARASOUL_EXEC_LIST[0]}
    #IFS="," PARASOUL_EXEC_LIST=( ${PARASOUL_EXEC_LIST[@]:1} )

    IFS="," PARASOUL_EXEC_LIST=( $(IFS=,; echo "${PARASOUL_EXEC_LIST[*]:1}") )
    export IFS="${ORIGIN_IFS}"
    if [[ -n ${item} ]];then
        exec {FD}< <(parasoul::exec::command "$item")
        FD_LIST=(${FD_LIST[@]} ${FD})
    fi
}

parasoul::main() {
    FD_LIST=()
    if [[ ! ${PARASOUL_DEAULT_SILENT_MODE} = 1 ]];then
        echo "start parallel: ${PARASOUL_EXEC_CMD} ";
        echo;
    fi

    while true; do
        for x in $(seq "${PARASOUL_DEAULT_JOBS}"); do
            parasoul::job_pack
        done
        wait

        if [[ ${PARASOUL_DEAULT_SILENT_MODE} = 1 ]];then
            for x in ${FD_LIST[@]}; do
                : <&${x}
            done
        else
            for x in ${FD_LIST[@]}; do
                cat <&${x}
            done
        fi

        if [[ -z ${PARASOUL_EXEC_LIST[@]} ]];then
            break
        fi
    done
}


optspec=":j:m:c:d:F:-:hvVlsq"
while getopts "$optspec" optchar; do
    case "${optchar}" in
        -)
            case "${OPTARG}" in
                help)
                    parasoul::help; exit 1
                    ;;
                version)
                    parasoul::version; exit 1
                    ;;
                delimiter)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    PARASOUL_DEAULT_LIST_DELIMITER="${val}"
                    ;;
                pipe)
                    PARASOUL_PIPE_MODE="1"
                    ;;
                replace-token)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    PARASOUL_DEAULT_REPLACE_TOKEN="${val}"
                    ;;
                command)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    PARASOUL_EXEC_CMD="${val}"
                    ;;
                jobs)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    if [[ ${val} =~ ^[[:digit:]]+$ ]]; then
                        PARASOUL_DEAULT_JOBS="${val}"
                    else
                        echo "Unknown option --jobs ${val}" >&2
                        exit 1
                    fi
                    ;;
                quiet)
                    PARASOUL_DEAULT_QUIET_MODE="1"
                    ;;
                *)
                    echo "Unknown option --${OPTARG}" >&2
                    exit 1
                    ;;
            esac;;
        h)
            parasoul::help; exit 1
            ;;
        v)
            parasoul::version; exit 1
            ;;
        d)
            PARASOUL_DEAULT_LIST_DELIMITER="${OPTARG}"
            ;;
        p)
            PARASOUL_PIPE_MODE="1"
            ;;
        I)
            PARASOUL_DEAULT_REPLACE_TOKEN="${OPTARG}"
            ;;
        e)
            PARASOUL_EXEC_CMD="${val}"
            ;;
        j)
            if [[ ${OPTARG} =~ ^[[:digit:]]+$ ]]; then
                PARASOUL_DEAULT_JOBS="${OPTARG}"
            else
                echo "Unknown option -j ${OPTARG}" >&2
                exit 1
            fi
            ;;
        q)
            exit 1
            ;;
        *)
            if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))

parasoul::list::generate "$@"

if [[ -z ${PARASOUL_EXEC_CMD} ]];then
    echo "Error: '--command' is not given."
    exit 1
fi

parasoul::main && exit 0

